name: "Ion"
version: "Unspecified"
api-version: "1.19"

bootstrapper: net.horizonsend.ion.server.IonBootstrapper
loader: net.horizonsend.ion.IonLoader
main: net.horizonsend.ion.server.IonServer
load: STARTUP

dependencies:
  - name: WorldEdit
    required: true

  - name: UnifiedMetrics
    required: true

  - name: Citizens
    required: false

  - name: DiscordSRV
    required: false

  - name: LuckPerms
    required: false

  - name: Multiverse-Core
    required: false

  - name: Vault
    required: false

  - name: dynmap
    required: false

load-after:
  - name: WorldEdit
  - name: Citizens
  - name: DiscordSRV
  - name: LuckPerms
  - name: Multiverse-Core
  - name: Vault
  - name: dynmap
